<?php
@include("../../inc/header.php");

/*
		SoftName : EmpireBak
		Author   : wm_chief
		Copyright: Powered by www.phome.net
*/

E_D("DROP TABLE IF EXISTS `phome_enewsbqtemp`;");
E_C("CREATE TABLE `phome_enewsbqtemp` (
  `tempid` smallint(6) NOT NULL AUTO_INCREMENT,
  `tempname` varchar(60) NOT NULL DEFAULT '',
  `modid` smallint(6) NOT NULL DEFAULT '0',
  `temptext` text NOT NULL,
  `showdate` varchar(50) NOT NULL DEFAULT '',
  `listvar` text NOT NULL,
  `subnews` smallint(6) NOT NULL DEFAULT '0',
  `rownum` smallint(6) NOT NULL DEFAULT '0',
  `classid` smallint(6) NOT NULL DEFAULT '0',
  `docode` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`tempid`),
  KEY `classid` (`classid`)
) ENGINE=MyISAM AUTO_INCREMENT=38 DEFAULT CHARSET=utf8");
E_D("replace into `phome_enewsbqtemp` values('1','标题图片','4','[!--empirenews.listtemp--]<!--list.var1-->[!--empirenews.listtemp--]','Y-m-d H:i:s','<dl><dd><a href=\"[!--titleurl--]\"  title=\"[!--oldtitle--]\" target=\"_blank\"><img src=\"[!--titlepic--]\" /></a></dd><dt><a href=\"[!--titleurl--]\" title=\"[!--oldtitle--]\"  target=\"_blank\">[!--title--]</a></dt> </dl>','0','1','0','0');");
E_D("replace into `phome_enewsbqtemp` values('2','儿歌栏目页最多评分标图','4','[!--empirenews.listtemp--]<!--list.var1-->[!--empirenews.listtemp--]','Y-m-d H:i:s','\$pf0=round(\$r[infopfen]/\$r[infopfennum]);  \r\n\$listtemp=\\\\''<dl><dd><a href=\\\\\"[!--titleurl--]\\\\\" target=\\\\\"_blank\\\\\" title=\\\\\"[!--title--]\\\\\"><img src=\\\\\"[!--titlepic--]\\\\\"  width=\\\\\"69px\\\\\" /></a></dd> <dt><a href=\\\\\"[!--titleurl--]\\\\\" target=\\\\\"_blank\\\\\"  title=\\\\\"[!--title--]\\\\\">[!--title--]</a><p><i class=\\\\\"starAll star\\\\''.\$pf0.\\\\''\\\\\"></i></p></dt></dl>\\\\'';','0','1','0','1');");
E_D("replace into `phome_enewsbqtemp` values('3','分类页子栏目_92game','4','<a href=\\\\\"../\\\\\" class=\\\\\"current\\\\\" id=\\\\\"flhome\\\\\">全部</a>[!--empirenews.listtemp--]<!--list.var1-->[!--empirenews.listtemp--]','m-d','<a href=\\\\\"[!--classurl--]\\\\\" id=fl[!--classid--]>[!--classname--]</a>','60','1','0','0');");
E_D("replace into `phome_enewsbqtemp` values('4','播放页宝宝爱看','4','[!--empirenews.listtemp--]<!--list.var1-->[!--empirenews.listtemp--]','Y-m-d H:i:s','\$pf=round(\$r[infopfen]/\$r[infopfennum]);\r\n\$listtemp=''<dl><dd><a href=\"[!--titleurl--]\" target=\"_blank\" title=\"[!--title--]\"><img src=\"[!--titlepic--]\"  width=\"69px\" /></a></dd><dt><a href=\"[!--titleurl--]\" target=\"_blank\"  title=\"[!--title--]\">[!--title--]</a><p><i class=\"starAll star''.\$pf.''\"></i></p></dt></dl>'';\r\n','0','1','0','1');");
E_D("replace into `phome_enewsbqtemp` values('5','教案封面子栏目_92game','4','[!--empirenews.listtemp--]<!--list.var1-->[!--empirenews.listtemp--]','Y-m-d H:i:s','<li><a href=\\\\\"[!--classurl--]\\\\\" target=\\\\\"_blank\\\\\" title=\\\\\"[!--classname--]\\\\\">[!--classname--]</a></li>','56','1','0','1');");
E_D("replace into `phome_enewsbqtemp` values('7','栏目页文字列表','4','[!--empirenews.listtemp--]<!--list.var1-->[!--empirenews.listtemp--]\r\n','Y-m-d','\$listtemp=\\\\''<li>\\\\''.\$no.\\\\''.<a href=\\\\\"[!--titleurl--]\\\\\" target=\\\\\"_blank\\\\\">[!--title--]</a></li>\\\\'';','0','1','0','1');");
E_D("replace into `phome_enewsbqtemp` values('8','分类页总排行月排行32','4','[!--empirenews.listtemp--]\r\n<!--list.var1-->\r\n[!--empirenews.listtemp--]','Y-m-d H:i:s','if(\$no<6)\r\n{\r\n\r\n   \$pf=round(\$r[infopfen]/\$r[infopfennum],1);\r\n   \$bfs=round(\$r[infopfen]*20/\$r[infopfennum]);\r\n   \$addtext=\\\\''<dd><a href=\\\\\"[!--titleurl--]\\\\\" target=\\\\\"_blank\\\\\" ><img src=\\\\\"[!--titlepic--]\\\\\" alt=\\\\\"[!--oldtitle--]\\\\\" /></a><div class=\\\\\"games_description\\\\\"><h4><a href=\\\\\"[!--titleurl--]\\\\\" target=\\\\\"_blank\\\\\" >[!--title--]</a></h4><a href=\\\\\"[!--this.classlink--]\\\\\" class=\\\\\"gray_a\\\\\">[!--this.classname--]</a><span class=\\\\\"re-graded\\\\\"><code style=\\\\\"width:\\\\''.\$bfs.\\\\''%\\\\\">\\\\''.\$pf.\\\\''分</code></span></div></dd>\\\\'';\r\n   if(\$no==5)\r\n	\$addtext=\$addtext.\\\\\"<dt><ul>\\\\\";\r\n\r\n}\r\nelse\r\n{\r\n   \$addtext=\\\\''<li><a i=\\\\\"[!--titlepic--]\\\\\" href=\\\\\"[!--titleurl--]\\\\\" target=\\\\\"_blank\\\\\" >[!--title--]</a><a href=\\\\\"[!--this.classlink--]\\\\\" class=\\\\\"gray_a\\\\\">[!--this.classname--]</a></li>\\\\'';\r\n   if(\$no==32)\r\n	\$addtext=\$addtext.\\\\''</ul></dt>\\\\'';\r\n				   \r\n}\r\n\r\n \$listtemp=\$addtext;','150','1','0','1');");
E_D("replace into `phome_enewsbqtemp` values('13','内容页相关分类文字排行','4','[!--empirenews.listtemp--]<!--list.var1-->[!--empirenews.listtemp--]','Y-m-d H:i:s','\$listtemp=\\\\''<li rightrank=\\\\\"rightrank\\\\\" name=\\\\\"[!--title--]\\\\\" show=\\\\\"[!--id--]\\\\\" img=\\\\\"jpg\\\\\" score=\\\\\"8<em>.4</em>\\\\\" spicy=\\\\\"10\\\\\"><span class=\\\\\"sn\\\\''.\$no.\\\\''\\\\\">\\\\''.\$no.\\\\''</span><a href=\\\\\"[!--titleurl--]\\\\\" target=\\\\\"_blank\\\\\">[!--title--]</a><strong class=\\\\\"icon_up\\\\\"></strong></li>\\\\'';','0','1','0','1');");
E_D("replace into `phome_enewsbqtemp` values('14','列表图片排行','4','[!--empirenews.listtemp--]<!--list.var1-->[!--empirenews.listtemp--]','Y-m-d H:i:s','<dd><p><a href=\\\\\"[!--titleurl--]\\\\\"><img src=\\\\\"[!--titlepic--]\\\\\" alt=\\\\\"[!--title--]\\\\\" /></a><strong><a href=\\\\\"[!--titleurl--]\\\\\">[!--title--]</a></strong></p><span class=\\\\\"span_u\\\\\"></span></dd>','0','1','0','0');");
E_D("replace into `phome_enewsbqtemp` values('15','首页头条','4','[!--empirenews.listtemp--]<!--list.var1-->[!--empirenews.listtemp--]','Y-m-d H:i:s','<div><a href=\\\\\"[!--titleurl--]\\\\\" target=\\\\\"_blank\\\\\" ><img src=\\\\\"[!--titlepic--]\\\\\" /></a> <a href=\\\\\"[!--titleurl--]\\\\\"   target=\\\\\"_blank\\\\\" class=\\\\\"rollred\\\\\">[!--title--]</a></div>','150','1','0','0');");
E_D("replace into `phome_enewsbqtemp` values('16','播放页同类游戏','4','[!--empirenews.listtemp--]<!--list.var1-->[!--empirenews.listtemp--]','Y-m-d H:i:s','<li rel=\\\\\"[!--id--]\\\\\" ><a href=\\\\\"[!--titleurl--]\\\\\" target=\\\\\"_blank\\\\\" title=\\\\\"[!--oldtitle--]\\\\\"><img src=\\\\\"[!--titlepic--]\\\\\" alt=\\\\\"[!--oldtitle--]\\\\\"/><span class=\\\\\"txt\\\\\">[!--title--]</span></a></li>','150','1','0','0');");
E_D("replace into `phome_enewsbqtemp` values('17','儿歌_播放页儿童动画片','4','[!--empirenews.listtemp--]<!--list.var1-->[!--empirenews.listtemp--]','Y-m-d H:i:s','\$pf=round(\$r[infopfen]/\$r[infopfennum]);\r\n\$listtemp=\\\\''<li><span><a href=\\\\\"[!--titleurl--]\\\\\" target=\\\\\"_blank\\\\\"><img src=\\\\\"[!--titlepic--]\\\\\" width=\\\\\"81\\\\\"></a></span><p><b><a href=\\\\\"[!--titleurl--]\\\\\" target=\\\\\"_blank\\\\\" title=\\\\\"[!--title--]\\\\\">[!--title--]</a></b><s class=\\\\\"starAll star\\\\''.\$pf.\\\\'' mb10\\\\\"></s><a class=\\\\\"look\\\\\" href=\\\\\"[!--titleurl--]\\\\\" target=\\\\\"_blank\\\\\">马上观看</a></p></li>\\\\'';','150','1','0','1');");
E_D("replace into `phome_enewsbqtemp` values('18','首页每日推荐','4','[!--empirenews.listtemp--]<!--list.var1-->[!--empirenews.listtemp--]','Y-m-d H:i:s','\$pf=round(\$r[infopfen]/\$r[infopfennum],1); \r\nif(\$no<4)\r\n{\r\n	\$addtext=\\\\''<dl rightpic=\\\\\"rightpic\\\\\" name=\\\\\"[!--title--]\\\\\" show=\\\\\"[!--id--]\\\\\" img=\\\\\"jpg\\\\\" score=\\\\\"\\\\''.\$pf.\\\\''\\\\\" spicy=\\\\\"9\\\\\"><dt><a href=\\\\\"[!--titleurl--]\\\\\"><img  src=\\\\\"[!--titlepic--]\\\\\"></a></dt><dd><a href=\\\\\"[!--titleurl--]\\\\\">[!--title--]</a><span>[[!--this.classname--]]</span></dd></dl>\\\\'';\r\n    if(\$no==3)\r\n	\$addtext=\$addtext.\\\\''<ol id=\\\\\"everydayGameList\\\\\">\\\\'';\r\n}\r\nelse\r\n{\r\n	\$addtext=\\\\''<li right=\\\\\"right\\\\\" name=\\\\\"[!--title--]\\\\\" show=\\\\\"[!--id--]\\\\\" img=\\\\\"jpg\\\\\" score=\\\\\"\\\\''.\$pf.\\\\''\\\\\" spicy=\\\\\"10\\\\\"><p><a href=\\\\\"[!--titleurl--]\\\\\" >[!--title--]</a></p><span>[[!--this.classname--]]</span></li>\\\\'';\r\n     if(\$no==21)\r\n	\$addtext=\$addtext.\\\\''</ol>\\\\''; \r\n}\r\n \$listtemp=\$addtext;','150','1','0','1');");
E_D("replace into `phome_enewsbqtemp` values('19','宝宝都喜欢看的','4','[!--empirenews.listtemp--]<!--list.var1-->[!--empirenews.listtemp--]','Y-m-d H:i:s','\$pf=round(\$r[infopfen]/\$r[infopfennum]);\r\n\$listtemp=''<li><span><a href=\"[!--titleurl--]\" target=\"_blank\"><img src=\"[!--titlepic--]\" width=\"81\"></a></span><p><b><a href=\"[!--titleurl--]\" target=\"_blank\" title=\"[!--title--]\">[!--title--]</a></b><s class=\"starAll star''.\$pf.'' mb10\"></s><a class=\"look\" href=\"[!--titleurl--]\" target=\"_blank\">马上观看</a></p></li>'';\r\n','150','1','0','1');");
E_D("replace into `phome_enewsbqtemp` values('20','分类页相关合集','4','[!--empirenews.listtemp--]<!--list.var1-->[!--empirenews.listtemp--]','Y-m-d H:i:s','<li>  \r\n  	<a href=\\\\\"/tag/[!--tagdir--]/\\\\\" class=\\\\\"pic\\\\\" title=\\\\\"[!--tagname--]合集\\\\\" target=\\\\\"_blank\\\\\"><img src=\\\\\"[!--spic--]\\\\\" alt=\\\\\"[!--tagname--]\\\\\"><s></s></a>\r\n	<div class=\\\\\"txt\\\\\">\r\n    	<p><a href=\\\\\"/tag/[!--tagdir--]/\\\\\" title=\\\\\"[!--tagname--]合集\\\\\" target=\\\\\"_blank\\\\\">[!--tagname--]合集</a></p>\r\n        <span>含[!--num--]款</span>\r\n     </div>\r\n</li>\r\n','150','1','0','1');");
E_D("replace into `phome_enewsbqtemp` values('21','最新儿歌页图文','4','[!--empirenews.listtemp--]<!--list.var1-->[!--empirenews.listtemp--]','Y-m-d H:i:s','<dl><dd><a href=\\\\\"[!--titleurl--]\\\\\" target=\\\\\"_blank\\\\\"><img src=\\\\\"[!--titlepic--]\\\\\" title=\\\\\"[!--title--]\\\\\" /></a></dd><dt><a href=\\\\\"[!--titleurl--]\\\\\" target=\\\\\"_blank\\\\\">[!--title--]</a></dt></dl>','56','1','0','1');");
E_D("replace into `phome_enewsbqtemp` values('22','首页文字','4','[!--empirenews.listtemp--]<!--list.var1-->[!--empirenews.listtemp--]','Y-m-d H:i:s','<a href=\\\\\"[!--titleurl--]\\\\\"  target=\\\\\"_blank\\\\\">[!--title--]</a> ','150','1','0','1');");
E_D("replace into `phome_enewsbqtemp` values('23','童话首页最新最热文字','4','[!--empirenews.listtemp--]<!--list.var1-->[!--empirenews.listtemp--]','Y-m-d H:i:s','<li><a href=\\\\\"[!--titleurl--]\\\\\" target=\\\\\"_blank\\\\\" >[!--title--]</a><span><i>[!--onclick--]</i>次</span></li>','180','1','0','0');");
E_D("replace into `phome_enewsbqtemp` values('24','儿歌网站地图子栏目','4','[!--empirenews.listtemp--]<!--list.var1-->[!--empirenews.listtemp--]','Y-m-d H:i:s','<a href=\\\\\"[!--classurl--]\\\\\" id=fl[!--classid--]>[!--classname--]</a>&nbsp;&nbsp;','20','1','0','0');");
E_D("replace into `phome_enewsbqtemp` values('25','谜语封面最新谜语','4','[!--empirenews.listtemp--]<!--list.var1-->[!--empirenews.listtemp--]','m-d','<li><a href=\\\\\"[!--titleurl--]\\\\\" target=\\\\\"_blank\\\\\" class=\\\\\"content lzy_my_content\\\\\">[!--title--]</a><span>[!--newstime--]</span></li>','0','1','0','0');");
E_D("replace into `phome_enewsbqtemp` values('26','儿歌首页排行榜top10','4','[!--empirenews.listtemp--]<!--list.var1-->[!--empirenews.listtemp--]','Y-m-d H:i:s','<li><a href=\\\\\"[!--titleurl--]\\\\\" class=\\\\\"blue\\\\\" target=\\\\\"_blank\\\\\">[!--title--]</a><a href=\\\\\"[!--this.classlink--]\\\\\" class=\\\\\"fl\\\\\"  target=\\\\\"_blank\\\\\">[[!--this.classname--]]</a><div class=\\\\\"c\\\\\"></div></li>','50','1','0','0');");
E_D("replace into `phome_enewsbqtemp` values('27','儿歌首页热门儿歌','4','[!--empirenews.listtemp--]<!--list.var1-->[!--empirenews.listtemp--]','m-d','<div><a href=\\\\\"[!--titleurl--]\\\\\" target=\\\\\"_blank\\\\\" ><img src=\\\\\"[!--titlepic--]\\\\\" /></a> <a href=\\\\\"[!--titleurl--]\\\\\"   target=\\\\\"_blank\\\\\" class=\\\\\"rollred\\\\\">[!--title--]</a></div>','100','1','0','0');");
E_D("replace into `phome_enewsbqtemp` values('28','标题li','4','[!--empirenews.listtemp--]<!--list.var1-->[!--empirenews.listtemp--]','m-d','<li><a href=\\\\\"[!--titleurl--]\\\\\"  target=\\\\\"_blank\\\\\" title=\\\\\"[!--title--]\\\\\" >[!--title--]</a></li>','100','1','0','0');");
E_D("replace into `phome_enewsbqtemp` values('29','儿歌首页_专题','4','[!--empirenews.listtemp--]<!--list.var1-->[!--empirenews.listtemp--]','Y-m-d H:i:s',' <dl>\r\n            <dd> <a href=\\\\\"[!--classurl--]\\\\\" target=\\\\\"_blank\\\\\" ><img border=\\\\\"0\\\\\" src=\\\\\"[!--classimg--]\\\\\"  alt=\\\\\"[!--classname--]\\\\\" /></a> </dd>\r\n            <dt> <a href=\\\\\"[!--classurl--]\\\\\" target=\\\\\"_blank\\\\\">[!--classname--]</a> </dt>\r\n          </dl>','150','1','0','0');");
E_D("replace into `phome_enewsbqtemp` values('30','童话首页各分类文字','4','[!--empirenews.listtemp--]<!--list.var1-->[!--empirenews.listtemp--]','m-d','<li><a href=\\\\\"[!--titleurl--]\\\\\" target=\\\\\"_blank\\\\\">[!--title--]</a><span><i>点击率:[!--onclick--]</i></span></li>','50','1','0','0');");
E_D("replace into `phome_enewsbqtemp` values('31','播放页右侧相关','4','[!--empirenews.listtemp--]<!--list.var1-->[!--empirenews.listtemp--]','m-d','<li><a href=\\\\\"[!--titleurl--]\\\\\" target=\\\\\"_blank\\\\\" title=\\\\\"[!--title--]\\\\\"><img src=\\\\\"[!--titlepic--]\\\\\" width=\\\\\"59px\\\\\"/>[!--title--]</a></li>','50','1','0','0');");
E_D("replace into `phome_enewsbqtemp` values('32','教案头条','4','[!--empirenews.listtemp--]<!--list.var1-->[!--empirenews.listtemp--]','m-d','<a href=\\\\\"[!--titleurl--]\\\\\" target=\\\\\"_blank\\\\\"><img src=\\\\\"/images/jiaoan_artical.gif\\\\\" width=\\\\\"126\\\\\" height=\\\\\"126\\\\\" /></a><ul class=\\\\\"box3_l_ul\\\\\">\r\n<h3><a href=\\\\\"[!--titleurl--]\\\\\" target=\\\\\"_blank\\\\\">[!--title--]</a></h3>\r\n[!--smalltext--]','50','1','0','0');");
E_D("replace into `phome_enewsbqtemp` values('33','教案分类页子栏目_92game','4','[!--empirenews.listtemp--]<li  class=\\\\\"Listbg\\\\\"><!--list.var1--></li><li><!--list.var2--></li>[!--empirenews.listtemp--]','m-d','<a href=\\\\\"[!--classurl--]\\\\\">[!--classname--]</a> ','60','2','0','0');");
E_D("replace into `phome_enewsbqtemp` values('34','经典儿歌图文','4','[!--empirenews.listtemp--]<!--list.var1-->[!--empirenews.listtemp--]','m-d','<div class=\"pictrue2\" style=\"margin-left:30px;width:120px\">\r\n<a href=\"[!--titleurl--]\" target=\"_blank\"><img src=\"[!--titlepic--]\" /></a><br>\r\n<a href=\"[!--titleurl--]\" target=\"_blank\">[!--title--]</a>\r\n</div>','50','1','0','0');");
E_D("replace into `phome_enewsbqtemp` values('35','经典儿歌文字','4','[!--empirenews.listtemp--]<!--list.var1-->[!--empirenews.listtemp--]','m-d','<div class=\"web\" style=\"margin-left:12px\"><img src=\"images/img9.jpg\" /><a href=\"[!--titleurl--]\" target=\"_blank\">[!--title--]</a></div>','50','1','0','0');");
E_D("replace into `phome_enewsbqtemp` values('36','经典儿歌文字2','4','[!--empirenews.listtemp--]<!--list.var1-->[!--empirenews.listtemp--]','m-d','<div class=\"web2\" style=\"margin-left:5px\"><img src=\"images/img9.jpg\" /><a href=\"[!--titleurl--]\" target=\"_blank\">[!--title--]</a></div>','50','1','0','0');");
E_D("replace into `phome_enewsbqtemp` values('37','经典儿歌文字排行','4','[!--empirenews.listtemp--]<!--list.var1-->[!--empirenews.listtemp--]','m-d','\$listtemp=''<div class=\"part9\" ><div class=\"part10\"><div class=\"d\"><b>''.\$no.''</b></div></div><img src=\"images/img31.jpg\" /><a href=\"[!--titleurl--]\" target=\"_blank\">[!--title--]</a></div>'';\r\n','50','1','0','1');");

@include("../../inc/footer.php");
?>