<?php
@include("../../inc/header.php");

/*
		SoftName : EmpireBak
		Author   : wm_chief
		Copyright: Powered by www.phome.net
*/

E_D("DROP TABLE IF EXISTS `phome_ecms_infoclass_news`;");
E_C("CREATE TABLE `phome_ecms_infoclass_news` (
  `classid` int(11) NOT NULL DEFAULT '0',
  `zz_title` text NOT NULL,
  `z_title` varchar(255) NOT NULL DEFAULT '',
  `qz_title` varchar(255) NOT NULL DEFAULT '',
  `save_title` varchar(10) NOT NULL DEFAULT '',
  `zz_titlepic` text NOT NULL,
  `z_titlepic` varchar(255) NOT NULL DEFAULT '',
  `qz_titlepic` varchar(255) NOT NULL DEFAULT '',
  `save_titlepic` varchar(10) NOT NULL DEFAULT '',
  `zz_newstime` text NOT NULL,
  `z_newstime` varchar(255) NOT NULL DEFAULT '',
  `qz_newstime` varchar(255) NOT NULL DEFAULT '',
  `save_newstime` varchar(10) NOT NULL DEFAULT '',
  `zz_ftitle` text NOT NULL,
  `z_ftitle` varchar(255) NOT NULL DEFAULT '',
  `qz_ftitle` text NOT NULL,
  `save_ftitle` varchar(10) NOT NULL DEFAULT '',
  `zz_smalltext` text NOT NULL,
  `z_smalltext` varchar(255) NOT NULL DEFAULT '',
  `qz_smalltext` text NOT NULL,
  `save_smalltext` varchar(10) NOT NULL DEFAULT '',
  `zz_writer` text NOT NULL,
  `z_writer` varchar(255) NOT NULL DEFAULT '',
  `qz_writer` text NOT NULL,
  `save_writer` varchar(10) NOT NULL DEFAULT '',
  `zz_befrom` text NOT NULL,
  `z_befrom` varchar(255) NOT NULL DEFAULT '',
  `qz_befrom` text NOT NULL,
  `save_befrom` varchar(10) NOT NULL DEFAULT '',
  `zz_newstext` text NOT NULL,
  `z_newstext` varchar(255) NOT NULL DEFAULT '',
  `qz_newstext` varchar(255) NOT NULL DEFAULT '',
  `save_newstext` varchar(10) NOT NULL DEFAULT '',
  `zz_diggtop` text NOT NULL,
  `z_diggtop` varchar(255) NOT NULL DEFAULT '',
  `qz_diggtop` text NOT NULL,
  `save_diggtop` varchar(10) NOT NULL DEFAULT '',
  `zz_author` text NOT NULL,
  `z_author` varchar(255) NOT NULL,
  `qz_author` varchar(255) NOT NULL,
  `save_author` varchar(10) NOT NULL,
  PRIMARY KEY (`classid`),
  KEY `classid` (`classid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8");
E_D("replace into `phome_ecms_infoclass_news` values('57','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('58','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('59','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('60','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('61','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('62','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('63','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('64','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('65','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('66','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('67','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('68','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('69','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('70','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('71','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('72','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('73','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('74','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('75','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('76','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('77','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('78','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('79','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('80','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('81','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('82','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('83','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('84','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('85','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('86','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('87','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('88','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('89','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('90','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('91','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('92','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('93','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('94','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('95','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('96','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('97','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('98','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('99','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('100','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('101','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('102','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('103','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('104','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('105','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('106','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('107','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('108','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('109','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('110','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('111','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('112','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('113','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('114','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('115','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('116','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('117','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('118','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('119','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('120','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('121','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('122','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('123','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('124','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('125','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('126','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('127','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('128','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('129','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('130','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('131','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('132','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('133','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('134','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('135','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('136','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('137','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('138','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('139','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('140','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('141','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('142','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('143','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('144','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('145','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('146','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('147','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('148','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('149','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('150','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('151','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('152','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('153','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('154','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('155','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('156','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('157','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('158','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('159','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('160','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('161','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('162','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('163','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('164','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('165','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('166','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('167','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('168','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('169','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('170','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('171','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('172','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('173','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('174','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('175','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('176','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('177','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('178','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('179','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('180','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('181','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('182','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('183','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('184','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('185','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('186','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('187','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('188','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('189','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('190','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('191','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('192','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('193','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('194','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('195','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('196','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('197','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('198','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('199','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','',' <label id=\\\\\"midi\\\\\" style=\\\\\"display:none\\\\\">[!--smalltext--]</label>','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--] <br/><br/>','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('201','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--]<div class=\\\\\"thpage\\\\\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('202','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--]<div class=\\\\\"thpage\\\\\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('203','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--]<div class=\\\\\"thpage\\\\\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('204','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--]<div class=\\\\\"thpage\\\\\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('205','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--]<div class=\\\\\"thpage\\\\\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('206','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--]<div class=\\\\\"thpage\\\\\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('207','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--]<div class=\\\\\"thpage\\\\\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('208','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--]<div class=\\\\\"thpage\\\\\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('209','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--]<div class=\\\\\"thpage\\\\\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('210','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--]<div class=\\\\\"thpage\\\\\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('211','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\\\\\"tag\\\\\">[!--smalltext--]</div>* <div class=\\\\\"cnt-main-n\\\\\">','','','','','','','','','','','','<div class=\\\\\"cnt-main-n\\\\\">[!--newstext--]</div>*<div class=\\\\\"Share\\\\\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('212','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('213','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('214','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('215','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('216','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('217','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('218','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('219','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('220','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('221','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('222','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('223','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('224','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('225','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('226','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('227','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('228','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('229','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('230','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('231','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('232','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('233','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('234','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('235','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('236','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('237','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('238','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('239','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('240','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('241','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('242','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('243','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('244','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('245','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('246','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('247','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('248','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('249','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('250','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('251','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('252','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('253','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('254','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('255','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('256','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('257','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('258','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('259','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('260','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('261','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('262','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('263','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('264','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('265','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('266','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('267','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('268','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('269','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('270','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('271','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('272','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('273','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('274','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('275','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('276','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('277','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('278','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('279','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('280','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('281','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('282','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('283','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('284','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('285','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('286','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('287','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('288','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('289','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('290','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('291','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('292','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('293','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('294','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('295','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('296','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('297','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('298','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('299','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('300','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('301','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('302','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('303','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('304','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('305','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('306','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('307','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('308','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('309','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('310','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('311','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('312','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('313','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('314','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('315','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('316','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('317','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('318','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('319','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('320','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('321','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('322','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('323','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('324','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('325','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('326','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('327','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('328','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('329','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('330','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('331','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('332','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");
E_D("replace into `phome_ecms_infoclass_news` values('333','<h1>[!--title--]</h1>','','','','','','','','','','','','','','','','<div class=\"tag\">[!--smalltext--]</div>* <div class=\"cnt-main-n\">','','','','','','','','','','','','<div class=\"cnt-main-n\">[!--newstext--]</div>*<div class=\"Share\">','','','','','','','','','','','');");

@include("../../inc/footer.php");
?>